feat: kfp-viz sidecar rewrite with base charm (#309)
based on #305 due to unverified commits

Rewrite the `kfp-viz` charm, migrating it from podspec to sidecar using the reusable base charm in charmed-kubeflow-chisme. More details on the base charm [in this README.md](https://github.com/canonical/charmed-kubeflow-chisme/tree/main/src/charmed_kubeflow_chisme/components#readme)
# Summary of changes
- rewrites all charm logic in terms of Components
- implements the Pebble container
- implements the relation handler
- refactors the unit tests to use the base charm tooling
- modifies requirements.in and requirements-unit.in and updates the requirements-*.txt's

**NOTE:** Due to deployment parameter in PodSpec version, kfp-persistence cannot be upgraded using Juju refresh:
juju.errors.JujuAPIError: Juju on containers does not support updating deployment info for services.
Upgrade will be done by re-deploying the charm.

Need to update bunde definition to include trust: https://github.com/canonical/bundle-kubeflow/blob/main/releases/latest/edge/bundle.yaml#L120