Kf 3597 feat base class charm - kfp persistence (#268)
Initial version of base-class based KFP Persistence Agent charm.

Summary of changes:

Re-wrote charm using base-class framework.
Added integration tests local to the charm (minimal). Will rely on bundle level (top level integration tests).
Modified unit tests to be aligned with new framework.
NOTE: Due to deployment parameter in PodSpec version, kfp-persistence cannot be upgraded using Juju refresh:
juju.errors.JujuAPIError: Juju on containers does not support updating deployment info for services.
Upgrade will be done by re-deploying the charm.